In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dtree.csv")
df.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [3]:
df.shape

(400, 5)

In [4]:
df.isnull().sum()

User ID            0
Gender             0
Age                2
EstimatedSalary    2
Purchased          0
dtype: int64

In [10]:
X = df.iloc[:,2:4].values
Y = df.iloc[:,4].values

In [12]:
X

array([[1.90e+01, 1.90e+04],
       [3.50e+01, 2.00e+04],
       [2.60e+01, 4.30e+04],
       [2.70e+01, 5.70e+04],
       [1.90e+01, 7.60e+04],
       [2.70e+01, 5.80e+04],
       [2.70e+01, 8.40e+04],
       [3.20e+01, 1.50e+05],
       [2.50e+01, 3.30e+04],
       [3.50e+01, 6.50e+04],
       [2.60e+01, 8.00e+04],
       [2.60e+01, 5.20e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.80e+04],
       [1.80e+01, 8.20e+04],
       [2.90e+01, 8.00e+04],
       [4.70e+01, 2.50e+04],
       [4.50e+01, 2.60e+04],
       [4.60e+01, 2.80e+04],
       [4.80e+01, 2.90e+04],
       [4.50e+01, 2.20e+04],
       [4.70e+01, 4.90e+04],
       [4.80e+01, 4.10e+04],
       [4.50e+01, 2.20e+04],
       [4.60e+01, 2.30e+04],
       [4.70e+01, 2.00e+04],
       [4.90e+01,      nan],
       [4.70e+01, 3.00e+04],
       [2.90e+01, 4.30e+04],
       [3.10e+01, 1.80e+04],
       [3.10e+01, 7.40e+04],
       [2.70e+01, 1.37e+05],
       [2.10e+01, 1.60e+04],
       [2.80e+01, 4.40e+04],
       [2.70e+

In [16]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan , strategy='mean')

In [17]:
X = imputer.fit_transform(X)

In [18]:
X

array([[1.90000000e+01, 1.90000000e+04],
       [3.50000000e+01, 2.00000000e+04],
       [2.60000000e+01, 4.30000000e+04],
       [2.70000000e+01, 5.70000000e+04],
       [1.90000000e+01, 7.60000000e+04],
       [2.70000000e+01, 5.80000000e+04],
       [2.70000000e+01, 8.40000000e+04],
       [3.20000000e+01, 1.50000000e+05],
       [2.50000000e+01, 3.30000000e+04],
       [3.50000000e+01, 6.50000000e+04],
       [2.60000000e+01, 8.00000000e+04],
       [2.60000000e+01, 5.20000000e+04],
       [2.00000000e+01, 8.60000000e+04],
       [3.20000000e+01, 1.80000000e+04],
       [1.80000000e+01, 8.20000000e+04],
       [2.90000000e+01, 8.00000000e+04],
       [4.70000000e+01, 2.50000000e+04],
       [4.50000000e+01, 2.60000000e+04],
       [4.60000000e+01, 2.80000000e+04],
       [4.80000000e+01, 2.90000000e+04],
       [4.50000000e+01, 2.20000000e+04],
       [4.70000000e+01, 4.90000000e+04],
       [4.80000000e+01, 4.10000000e+04],
       [4.50000000e+01, 2.20000000e+04],
       [4.600000

In [19]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.25 , random_state=0)

In [24]:
#feature scalling
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)

In [25]:
from sklearn.svm import SVC
svcmodel = SVC(kernel='linear',random_state=0)

In [27]:
svcmodel.fit(X_train,Y_train)

SVC(kernel='linear', random_state=0)

In [28]:
Y_pred = svcmodel.predict(X_test)
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [29]:
Y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [30]:
#creation of confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)
cm

array([[63,  5],
       [ 7, 25]], dtype=int64)